### ISSUE TITLE
Help getting the emacs_module compiling [Nim devel v0.18.1]

### ISSUE THREAD

**Issue by kaushalmodi** [yuutayamada/nim-emacs-module#2]
Hello,

I tried these steps, but the GCC compilation is failing

## Steps

```
git clone https://github.com/yuutayamada/nim-emacs-module
cd nim-emacs-module/test
make
```

I get the same error even when I run `nim c --out:sample.so --app:lib sample.nim` from the `test/` dir.

## Error

```
Hint: streams [Processing]
Hint: cpuinfo [Processing]
Hint: linux [Processing]
CC: emacs_module_sample
CC: stdlib_times
CC: stdlib_posix
CC: stdlib_ospaths
CC: stdlib_osproc
CC: stdlib_strtabs
CC: stdlib_hashes
CC: stdlib_streams
Error: execution of an external compiler program 'gcc -c  -w -fPIC  -I/home/kmodi/stow/pkgs/nim/devel/lib -o /home/kmodi/stow/pub_dotfiles/emacs/dot-emacs.d/misc/nim-emacs-module/test/nimcache/emacs_module_sample.o /home/kmodi/stow/pub_dotfiles/emacs/dot-emacs.d/misc/nim-emacs-module/test/nimcache/emacs_module_sample.c' failed with exit code: 1

/home/kmodi/stow/pub_dotfiles/emacs/dot-emacs.d/misc/nim-emacs-module/test/nimcache/emacs_module_sample.c:28:10: error: unknown type name ‘emacs_env’
 provide (emacs_env *env, const char *feature)
          ^~~~~~~~~
/home/kmodi/stow/pub_dotfiles/emacs/dot-emacs.d/misc/nim-emacs-module/test/nimcache/emacs_module_sample.c:39:16: error: unknown type name ‘emacs_env’
 bind_function (emacs_env *env, const char *name, emacs_value Sfun)
                ^~~~~~~~~
/home/kmodi/stow/pub_dotfiles/emacs/dot-emacs.d/misc/nim-emacs-module/test/nimcache/emacs_module_sample.c:39:50: error: unknown type name ‘emacs_value’
```

Looks like I am missing an important step somewhere?

## Version

- Emacs `master` branch updated today (emacs 27+)
- Nim `devel` branch updated today (Nim 0.18.1+)
- gcc 7.2.0
- OS RHEL 6.6

**Comment by kaushalmodi** [comment]
I don't know C, but comparing with http://diobla.info/blog-archive/modules-tut.html, I see that the `#include <emacs-module.h>` line is missing in the Nim created *test/nimcache/emacs_module_sample.c*. Even if I add that manually to the C file, and manually run the gcc command after adding `-I.`, I get this other error:

```
km²~/stow/:../misc/nim-emacs-module/test> gcc -c -w -fPIC -I/home/kmodi/stow/pkgs/nim/devel/lib -o /home/kmodi/stow/pub_dotfiles/emacs/dot-emacs.d/misc/nim-emacs-module/test/nimcache/emacs_module_sample.o /home/kmodi/stow/pub_dotfiles/emacs/dot-emacs.d/misc/nim-emacs-module/test/nimcache/emacs_module_sample.c -I.
/home/kmodi/stow/pub_dotfiles/emacs/dot-emacs.d/misc/nim-emacs-module/test/nimcache/emacs_module_sample.c: In function ‘emacs_module_init’:
/home/kmodi/stow/pub_dotfiles/emacs/dot-emacs.d/misc/nim-emacs-module/test/nimcache/emacs_module_sample.c:58:38: error: ‘nimEmacs_sample_mod_test_return_t’ undeclared (first use in this function)
   DEFUN ("sample-mod-test-return-t", nimEmacs_sample_mod_test_return_t, 1, 1, NULL, NULL);
```

**Comment by kaushalmodi** [comment]
Here is the latest [`emacs-module.h`][1]. Does the `emacs-module.nim` need to change for that? I noticed one thing that a struct is named `emacs_env_26` instead of `emacs_env_25`. I made that change in `emacs-module.nim`, but I still get the same error.

---

**Update**: Actually ignore this comment..I see that the emacs-module.h has both `emacs_env_25` and `emacs_env_26`.

**Update 2 (2018/06/21)**: @Vindaar I have updated the `emacs-module.h` Gist link. It's built using emacs master branch (emacs 27+), but it should still work with emacs 25/26 (PS: emacs 26.1 is the latest stable release).

[1]: https://gist.github.com/kaushalmodi/3b899b27586a99ed3cc4da88a9bc12c3

**Comment by kaushalmodi** [comment]
@Lompik Looking at your past PR https://github.com/yuutayamada/nim-emacs-module/pull/1, it looks like you can also help to this brain-storming. Can you please help out with this issue?

**Comment by kaushalmodi** [comment]
@Vindaar I don't know which OS you are using. But if you are using a GNU/Linux system, you will find the `emacs-module.h` under the `src/` dir in the release tarball here: https://ftp.gnu.org/gnu/emacs/emacs-26.1.tar.xz

You can check the same for releases for other OS's too: https://www.gnu.org/software/emacs/download.html.

**Comment by kaushalmodi** [comment]
I have committed `emacs-module.h` for various emacs versions here: https://github.com/kaushalmodi/nim-emacs-module/tree/master/include.

**Comment by kaushalmodi** [comment]
@Vindaar To keep you in loop, see the development here: 

- https://github.com/yuutayamada/nim-emacs-module/pull/3#commitcomment-29453843
- https://gitter.im/nim-lang/Nim?at=5b2be91b960fcd4eb9175615

There is a regression in Nim behavior on devel. I was finally able to have this compile on v0.18.0 thanks to @Lompik.

Now need to make this work on devel .. :)
